on:
  push:
     branches:
       - main

name: ðŸš€ Build and Deploy

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown", "remotes"))'

      # The following can be delted after blogdown 1.6 is on CRAN ---
      - name: Get development version of blogdown
        run: Rscript -e 'remotes::install_github("rstudio/blogdown")'
      # --------------------------------------------------------------

      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo()'

      - name: Build site with blogdown
        run: Rscript -e "blogdown::build_site()"

      - name: Deploy ðŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs



